export const DELETE_TASK = 'DELETE_TASK'

export const UPDATE_TASK = 'UPDATE_TASK'

export const ADD_TASK = 'ADD_TASK'

export const UPDATE_TASK_STATUS = 'UPDATE_TASK_STATUS'

export const SEARCH_TASK = 'SEARCH_TASK'

export const LOAD_TASKS = 'LOAD_TASKS'

export const GET_TASKS = 'GET_TASKS'

export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    
    LOGOUT: 'USERS_LOGOUT',

    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_FAILURE',

};