export const DELETE_TASK = 'DELETE_TASK'

export const UPDATE_TASK = 'UPDATE_TASK'

export const ADD_TASK = 'ADD_TASK'

export const UPDATE_TASK_STATUS = 'UPDATE_TASK_STATUS'

export const SEARCH_TASK = 'SEARCH_TASK'

export const LOAD_TASKS = 'LOAD_TASKS'

export const GET_TASKS = 'GET_TASKS'

export const userConstants = {

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    LOGOUT: 'USERS_LOGOUT',

};